name: CI/CD for Express.js on VPS

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/FleetQuest_Node  # Change to your project directory
            
            echo "Fetching latest code..."
            git fetch --all
            git reset --hard origin/main  # Reset to the latest version
            git pull origin main          # Pull the latest code

            echo "Installing dependencies..."
            npm install  # Install new dependencies

            echo "Applying database migrations..."
         npx prisma migrate deploy --schema=prisma/schema # Deploy migrations

            echo "Synchronizing Prisma schema..."
            npx prisma db pull  # Pull latest DB schema
            npx prisma generate # Generate Prisma client

            echo "Restarting application..."
            pm2 restart all  # Restart all PM2 processes

            echo "Deployment completed successfully!"
          EOF
